### ISSUE TITLE
2018 ipt-knowledgebase-theme-wp update???

### ISSUE THREAD

**Issue by ghost** [swashata/ipt-knowledgebase-theme-wp#22]
The theme update?

**Comment by swashata** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by swashata** [comment]
[GitMate.io](https://gitmate.io) thinks the label prediction failed because there are not enough labels. Three labels must have been set on at least three issues each.

The contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.
